@startuml
'https://plantuml.com/object-diagram

object London
object Washington
object Berlin
object NewYork
object Beijing

map CapitalCity {
 UK *-> London
 USA *--> Washington
 Germany *---> Berlin
}

Beijing --> Washington
NewYork --> CapitalCity::USA
@enduml
