@startuml
'https://plantuml.com/class-diagram

abstract class AbstractList{
  add(obj:Object)
  delete(obj:Object))
}
abstract AbstractCollection{
 getSize()
}
interface List{
  add(Eelete e)
}
interface Collection

List <|-- AbstractList
Collection <|-- AbstractCollection

Collection <|- List
AbstractCollection <|- AbstractList
AbstractList <|-- ArrayList


class ArrayList {
Object[] elementData
size()
}

enum TimeUnit {
DAYS
HOURS
MINUTES
}

@enduml